const mongoose = require('mongoose');
const db=require("../init")
const { Schema } = mongoose;

const BlockSchema = new Schema({
  Name:String,
  dName:String,
  dCode:String
});

const BlockModel = mongoose.model("Block", BlockSchema);

module.exports = BlockModel;


const block =[
    {
        Name:"धरसींवा",
        dName:"रायपुर",
        dCode:"CG04"  
    },
    {
        Name:"तिल्दा",
        dName:"रायपुर",
        dCode:"CG04"  
    },
    {
        Name:"आरंग",
        dName:"रायपुर",
        dCode:"CG04"  
    },
    {
        Name:"अभनपुर",
        dName:"रायपुर",
        dCode:"CG04"  
    },
    {
        Name:"रायपुर",
        dName:"रायपुर",
        dCode:"CG04"  
    },
    {
        Name:"कवर्धा",
        dName:"कबीरधाम",
        dCode:"CG09"  
    },
    {
        Name:"पंडरिया",
        dName:"कबीरधाम",
        dCode:"CG09"  
    },
    {
        Name:"बोड़ला",
        dName:"कबीरधाम",
        dCode:"CG09"  
    },
    {
        Name:"सहसपुर लोहारा",
        dName:"कबीरधाम",
        dCode:"CG09"  
    },
    {
        Name:"कांकेर",
        dName:"कांकेर",
        dCode:"CG19"  
    },
    {
        Name:"चारामा",
        dName:"कांकेर",
        dCode:"CG19"  
    },
    {
        Name:"नरहरपुर",
        dName:"कांकेर",
        dCode:"CG19"  
    },
    {
        Name:"भानुप्रतापपुर + अंतागढ़ + कोयलीबेड़ा",
        dName:"कांकेर",
        dCode:"CG19"  
    },
    {
        Name:"कटघोरा",
        dName:"कोरबा",
        dCode:"CG12"  
    },
    {
        Name:"करतला",
        dName:"कोरबा",
        dCode:"CG12"  
    },
    {
        Name:"कोरबा",
        dName:"कोरबा",
        dCode:"CG12"  
    },
    {
        Name:"पाली",
        dName:"कोरबा",
        dCode:"CG12"  
    },
    {
        Name:"हरदीबजार दीपका",
        dName:"कोरबा",
        dCode:"CG12"  
    },
    {
        Name:"पेंड्रा + गौरेला",
        dName:"कोरिया",
        dCode:"CG16"  
    },
    {
        Name:"बैकुंठपुर",
        dName:"कोरिया",
        dCode:"CG16"  
    },
    {
        Name:"भरतपुर",
        dName:"कोरिया",
        dCode:"CG16"  
    },
    {
        Name:"मनेंद्रगढ़ + चिरमिरी",
        dName:"कोरिया",
        dCode:"CG16"  
    },
    {
        Name:"मरवाही",
        dName:"कोरिया",
        dCode:"CG16"  
    },
    {
        Name:"खैरागढ़",
        dName:"खैरागढ़-छुईखदान-गंडई",
        dCode:""  
    },
    {
        Name:"छुईखदान",
        dName:"खैरागढ़-छुईखदान-गंडई",
        dCode:""  
    },
    {
        Name:"गंडई",
        dName:"खैरागढ़-छुईखदान-गंडई",
        dCode:""  
    },
    {
        Name:"गरियाबंद + मैनपुर + देवभोग",
        dName:"गरियाबंद",
        dCode:"CG23"  
    },
    {
        Name:"छुरा",
        dName:"गरियाबंद",
        dCode:"CG23"  
    },
    {
        Name:"फिंगेश्वर",
        dName:"गरियाबंद",
        dCode:"CG23"  
    },
    {
        Name:"कुनकुरी",
        dName:"जशपुर",
        dCode:"CG14"  
    },
    {
        Name:"जशपुर",
        dName:"जशपुर",
        dCode:"CG14"  
    },
    {
        Name:"दुलदुला + बगीचा",
        dName:"जशपुर",
        dCode:"CG14"  
    },
    {
        Name:"पत्थलगांव",
        dName:"जशपुर",
        dCode:"CG14"  
    },
    {
        Name:"फरसाबहार + कांसाबेल + मनोरा",
        dName:"जशपुर",
        dCode:"CG14"  
    },
    {
        Name:"अकलतरा + बलौदा",
        dName:"जांजगीर-चाम्पा",
        dCode:"CG11"  
    },
    {
        Name:"जैजैपुर",
        dName:"जांजगीर-चाम्पा",
        dCode:"CG11"  
    },
    {
        Name:"डभरा",
        dName:"जांजगीर-चाम्पा",
        dCode:"CG11"  
    },
    {
        Name:"नवागढ़",
        dName:"जांजगीर-चाम्पा",
        dCode:"CG11"  
    },
    {
        Name:"पामगढ़",
        dName:"जांजगीर-चाम्पा",
        dCode:"CG11"  
    },
    {
        Name:"मालखरौदा",
        dName:"जांजगीर-चाम्पा",
        dCode:"CG11"  
    },
    {
        Name:"सक्ती + बम्हनीडीह",
        dName:"जांजगीर-चाम्पा",
        dCode:"CG11"  
    },
    {
        Name:"दुर्ग",
        dName:"दुर्ग",
        dCode:"CG07"  
    },
    {
        Name:"धमधा",
        dName:"दुर्ग",
        dCode:"CG07"  
    },
    {
        Name:"पाटन",
        dName:"दुर्ग",
        dCode:"CG07"  
    },
    {
        Name:"भिलाई",
        dName:"दुर्ग",
        dCode:"CG07"  
    },
    {
        Name:"कुरुद",
        dName:"धमतरी",
        dCode:"CG04"  
    },
    {
        Name:"धमतरी",
        dName:"धमतरी",
        dCode:"CG04"  
    },
    {
        Name:"नगरी + कुकरेल",
        dName:"धमतरी",
        dCode:"CG04"  
    },
    {
        Name:"भखारा",
        dName:"धमतरी",
        dCode:"CG04"  
    },
    {
        Name:"मगरलोड",
        dName:"धमतरी",
        dCode:"CG04"  
    },
    {
        Name:"बलरामपुर + कुसमी + शंकरगढ़",
        dName:"बलरामपुर",
        dCode:"CG30"  
    },
    {
        Name:"रामचंद्रपुर + राजपुर",
        dName:"बलरामपुर",
        dCode:"CG30"  
    },
    {
        Name:"वाड्रफनगर",
        dName:"बलरामपुर",
        dCode:"CG30"  
    },
    {
        Name:"कसडोल",
        dName:"बलोदा बाजार",
        dCode:"CG22"  
    },
    {
        Name:"पलारी",
        dName:"बलोदा बाजार",
        dCode:"CG22"  
    },
    {
        Name:"बलौदा बाजार",
        dName:"बलोदा बाजार",
        dCode:"CG22"  
    },
    {
        Name:"बिलाईगढ़",
        dName:"बलोदा बाजार",
        dCode:"CG22"  
    },
    {
        Name:"सिमगा + भाटापारा",
        dName:"बलोदा बाजार",
        dCode:"CG22"  
    },
    {
        Name:"कोंडागांव",
        dName:"बस्तर संभाग",
        dCode:"CG17"  
    },
    {
        Name:"दंतेवाड़ा + सुकमा + बीजापुर",
        dName:"बस्तर संभाग",
        dCode:"CG17"  
    },
    {
        Name:"बस्तर + नारायणपुर",
        dName:"बस्तर संभाग",
        dCode:"CG17"  
    },
    {
        Name:"अर्जुन्दा + गुण्डरदेही",
        dName:"बालोद",
        dCode:"CG24"  
    },
    {
        Name:"गुरूर",
        dName:"बालोद",
        dCode:"CG24"  
    },
    {
        Name:"डौंडी",
        dName:"बालोद",
        dCode:"CG24"  
    },
    {
        Name:"डौंडीलोहारा",
        dName:"बालोद",
        dCode:"CG24"  
    },
    {
        Name:"बालोद",
        dName:"बालोद",
        dCode:"CG24"  
    },
    {
        Name:"तखतपुर",
        dName:"बिलासपुर",
        dCode:"CG10"  
    },
    {
        Name:"बिलासपुर",
        dName:"बिलासपुर",
        dCode:"CG10"  
    },
    {
        Name:"बिल्हा",
        dName:"बिलासपुर",
        dCode:"CG10"  
    },
    {
        Name:"मस्तूरी",
        dName:"बिलासपुर",
        dCode:"CG10"  
    },
    {
        Name:"सीपत",
        dName:"बिलासपुर",
        dCode:"CG10"  
    },
    {
        Name:"थानखम्हरिया",
        dName:"बेमेतरा",
        dCode:"CG25"  
    },
    {
        Name:"नवागढ़",
        dName:"बेमेतरा",
        dCode:"CG25"  
    },
    {
        Name:"बेमेतरा",
        dName:"बेमेतरा",
        dCode:"CG25"  
    },
    {
        Name:"बेरला",
        dName:"बेमेतरा",
        dCode:"CG25"  
    },
    {
        Name:"साजा",
        dName:"बेमेतरा",
        dCode:"CG25"  
    },
    {
        Name:"पिथौरा",
        dName:"महासमुंद",
        dCode:"CG06"  
    },
    {
        Name:"बसना + सरायपाली",
        dName:"महासमुंद",
        dCode:"CG06"  
    },
    {
        Name:"बागबाहरा",
        dName:"महासमुंद",
        dCode:"CG06"  
    },
    {
        Name:"महासमुंद",
        dName:"महासमुंद",
        dCode:"CG06"  
    },
    {
        Name:"पथरिया",
        dName:"मुंगेली",
        dCode:"CG28"  
    },
    {
        Name:"मुंगेली",
        dName:"मुंगेली",
        dCode:"CG28"  
    },
    {
        Name:"लोरमी",
        dName:"मुंगेली",
        dCode:"CG28"  
    },
    {
        Name:"मोहला मानपुर",
        dName:"मोहला-मानपुर-चौकी",
        dCode:""  
    },
    {
        Name:"अंबागढ़ चौकी",
        dName:"मोहला-मानपुर-चौकी",
        dCode:""  
    },
    {
        Name:"छुरिया",
        dName:"राजनांदगांव",
        dCode:"CG08"  
    },
    {
        Name:"डोंगरगढ़",
        dName:"राजनांदगांव",
        dCode:"CG08"  
    },
    {
        Name:"डोंगरगांव",
        dName:"राजनांदगांव",
        dCode:"CG08"  
    },
    {
        Name:"राजनांदगांव",
        dName:"राजनांदगांव",
        dCode:"CG08"  
    },
    {
        Name:"कापू",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"खरसिया",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"घरघोड़ा",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"तमनार + लैलूंगा",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"धरमजयगढ़ + कापू",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"धरमजयगढ़",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"पुसौर",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"बरमकेला",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"रायगढ़",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"सारंगढ",
        dName:"रायगढ़",
        dCode:"CG13"  
    },
    {
        Name:"अंबिकापुर",
        dName:"सरगुजा",
        dCode:"CG15"  
    },
    {
        Name:"उदयपुर + लखनपुर",
        dName:"सरगुजा",
        dCode:"CG15"  
    },
    {
        Name:"लुण्ड्रा",
        dName:"सरगुजा",
        dCode:"CG15"  
    },
    {
        Name:"सीतापुर + मैनपाट + बतौली",
        dName:"सरगुजा",
        dCode:"CG15"  
    },
    {
        Name:"बरमकेला",
        dName:"सारंगगढ़-बिलाईगढ़",
        dCode:""  
    },
    {
        Name:"बिलाईगढ़",
        dName:"सारंगगढ़-बिलाईगढ़",
        dCode:""  
    },
    {
        Name:"सारंगढ़",
        dName:"सारंगगढ़-बिलाईगढ़",
        dCode:""  
    },
    {
        Name:"ओड़गी + प्रेमनगर + रामानुजनगर",
        dName:"सूरजपुर",
        dCode:"CG29"  
    },
    {
        Name:"प्रतापपुर",
        dName:"सूरजपुर",
        dCode:"CG29"  
    },
    {
        Name:"भैयाथान",
        dName:"सूरजपुर",
        dCode:"CG29"  
    },
    {
        Name:"सूरजपुर",
        dName:"सूरजपुर",
        dCode:"CG29"  
    },

]


// db();

// BlockModel.insertMany(block).then(()=>{
//     console.log("saved Succse block");
// }).catch(()=>{
//     console.log("not savsed");
// })